org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.version=2.1.0
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

org.gradle.java.home=C:\\Program Files\\Java\\jdk-19
# Disable AAR metadata validation to work around corrupted SDK 35/36
android.disableCheckAarMetadata=true
